### ISSUE TITLE
Add function that compares ranks

### ISSUE THREAD

**Issue by andy5995** [TelluricDeckay/telluric_handeval#2]
The [evaluate function](https://github.com/TelluricDeckay/telluric-handeval/blob/6bd742cf036bb6fb575be2aca3a2524d2db15351/src/lib.rs#L47) will check a 5-card hand to determine the rank.

```
    pub enum HandRank {
        Nothing,
        Pair,
        TwoPair,
        ThreeOfAKind,
        Straight,
        Flush,
        FullHouse,
        FourOfAKind,
        StraightFlush,
        RoyalFlush,
        InvalidHand,
    }
```

What's still needed is a function to compare 2 or more hands in the event of a tie.

Examples:

* If 2 or more players get a pair, the highest pair. If the highest pairs are tied, then the next highest card in their hands.

* If 2 or more players get a straight, the highest card in the straight.

* If 2 or more playes get a full house, the highest three-of-a-kind.

**Comment by Jammyjamjamman** [comment]
Implemented in https://github.com/TelluricDeckay/telluric-handeval/tree/feat/hand-ordering . Comparator needs more testing.

**Comment by andy5995** [comment]
I quickly reviewed some tests today and saw that I didn't finish adding comparator tests for all the ranks. I'll take care of that.
